repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/joxa86/oxprecommit
    rev: v0.3.2
    hooks:
      - id: oxfmt
