# Expression generated by update.sh; do not edit it by hand!
rec {
  pname = "brave-origin-nightly";
  version = "1.95.12";
  channel = "nightly";
  flavor = "origin";

  archives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-ndZlHSXSq5KwLhQGMgthCXFsXQsT9l1VMcWIJNE4mcU=";
    };
    aarch64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-arm64.zip";
      hash = "sha256-OCN2BKF8lS4lGx3YKo3mJbu4LgyK7hZOfKahegZSHdo=";
    };
    x86_64-darwin = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-v${version}-darwin-x64.zip";
      hash = "sha256-VQaUzkZwPyBh2FMZs7XBRL1Y6qZdihshzy1bswsvz/U=";
    };
  };
}
