#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl nix jq
# shellcheck shell=bash
#
# Regenerates packages/brave-origin-nightly/release.nix.
# Run: bash packages/brave-origin-nightly/update.sh
#
# Source: GitHub releases API for brave/brave-browser. This is fresher and
# more complete than versions.brave.com (the index Brave publishes), which
# lags by hours and sometimes omits assets. Rate-limited to 60 req/hr
# unauthenticated — fine for a manually-run updater; set GITHUB_TOKEN to
# raise it if you script this.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
OUT_FILE="${SCRIPT_DIR}/release.nix"
API="https://api.github.com/repos/brave/brave-browser/releases?per_page=100"

sri_hash() {
  nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$1")"
}

# Newest release (by published_at) carrying a brave-origin-nightly amd64.deb.
releaseJson="$(curl -fsSL ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} "$API" \
  | jq -c '
      [ .[]
        | select(.assets | map(.name)
          | any(test("brave-origin-nightly_[0-9.]+_amd64\\.deb$")))
      ] | sort_by(.published_at) | last
    ')"
version="$(printf '%s' "$releaseJson" | jq -r '.tag_name' | sed 's/^v//')"
echo "=> brave-origin-nightly: ${version}" >&2

# Emit one platform entry if the release has that asset. Keeps ${version}
# interpolation so subsequent bumps only refresh hashes.
emit_archive_entry() {
  local name="$1" platform="$2"
  local url
  url="$(printf '%s' "$releaseJson" \
    | jq -r --arg n "$name" '.assets[] | select(.name == $n) | .browser_download_url')"
  [[ -z "$url" ]] && return 0
  local hash nixUrl
  hash="$(sri_hash "$url")"
  nixUrl="${url//${version}/\$\{version\}}"
  cat <<EOF
    ${platform} = {
      url = "${nixUrl}";
      hash = "${hash}";
    };
EOF
}

{
  echo '# Expression generated by update.sh; do not edit it by hand!'
  echo 'rec {'
  echo '  pname = "brave-origin-nightly";'
  echo "  version = \"${version}\";"
  echo '  channel = "nightly";'
  echo '  flavor = "origin";'
  echo ''
  echo '  archives = {'
  emit_archive_entry "brave-origin-nightly_${version}_arm64.deb"  "aarch64-linux"
  emit_archive_entry "brave-origin-nightly_${version}_amd64.deb"  "x86_64-linux"
  emit_archive_entry "brave-origin-v${version}-darwin-arm64.zip" "aarch64-darwin"
  emit_archive_entry "brave-origin-v${version}-darwin-x64.zip"   "x86_64-darwin"
  echo '  };'
  echo '}'
} > "$OUT_FILE"
echo "wrote ${OUT_FILE}" >&2
