#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl nix jq
# shellcheck shell=bash
#
# Regenerates packages/brave-origin-nightly/release.nix from Brave's release
# index. Run: bash packages/brave-origin-nightly/update.sh
#
# Trimmed from nixpkgs pkgs/applications/networking/browsers/brave/update.sh
# (NixOS/nixpkgs, MPL-2.0). Version + asset metadata comes from the same
# versions.brave.com index that https://dl.brave.com/install.sh reads.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
VERSIONS_URL="https://versions.brave.com/latest/brave-versions.json"
OUT_FILE="${SCRIPT_DIR}/release.nix"

sri_hash() {
  nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "$1")"
}

# Newest nightly release whose assets contain $tmpl with ${version} filled.
find_release_with_asset() {
  local versionsJson="$1" tmpl="$2"
  jq -c --arg tmpl "$tmpl" '
    [ .[]
      | select(.channel == "nightly")
      | . as $r
      | select(
          $r.github.assets | map(.name)
          | any(. == ($tmpl | gsub("\\$\\{version\\}"; $r.name)))
        )
    ] | sort_by(.published) | last
  ' <<<"$versionsJson"
}

emit_archive_entry() {
  local releaseJson="$1" version="$2" template="$3" platform="$4"
  local name="${template//\$\{version\}/$version}"
  local url
  url="$(jq -r --arg n "$name" '.github.assets[] | select(.name == $n) | .download_url' <<<"$releaseJson")"
  [[ -z "$url" ]] && return 0
  local hash nixUrl
  hash="$(sri_hash "$url")"
  nixUrl="${url//${version}/\$\{version\}}"
  cat <<EOF
    ${platform} = {
      url = "${nixUrl}";
      hash = "${hash}";
    };
EOF
}

versionsJson="$(curl --fail -s "$VERSIONS_URL")"
releaseJson="$(find_release_with_asset "$versionsJson" 'brave-origin-nightly_${version}_amd64.deb')"
version="$(jq -r '.name' <<<"$releaseJson")"
echo "=> brave-origin-nightly: ${version}" >&2

{
  echo '# Expression generated by update.sh; do not edit it by hand!'
  echo 'rec {'
  echo '  pname = "brave-origin-nightly";'
  echo "  version = \"${version}\";"
  echo '  channel = "nightly";'
  echo '  flavor = "origin";'
  echo ''
  echo '  archives = {'
  emit_archive_entry "$releaseJson" "$version" 'brave-origin-nightly_${version}_arm64.deb'  "aarch64-linux"
  emit_archive_entry "$releaseJson" "$version" 'brave-origin-nightly_${version}_amd64.deb'  "x86_64-linux"
  emit_archive_entry "$releaseJson" "$version" 'brave-origin-v${version}-darwin-arm64.zip' "aarch64-darwin"
  emit_archive_entry "$releaseJson" "$version" 'brave-origin-v${version}-darwin-x64.zip'   "x86_64-darwin"
  echo '  };'
  echo '}'
} > "$OUT_FILE"
echo "wrote ${OUT_FILE}" >&2
